version: "3.9"

services:
  todo-app:
    container_name: todo-react-typescript
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # Expose Nginx on port 80
    restart: always

